# Generated by Django 3.0.8 on 2020-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200827_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='pub_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
